// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhCnXBN1efbd2sEhtp2S4vGkZQTprSRWQ',
    appId: '1:1084522965422:web:b9d3601d243bd16539403f',
    messagingSenderId: '1084522965422',
    projectId: 'fir-flutter-codelab-cc3cb',
    authDomain: 'fir-flutter-codelab-cc3cb.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-cc3cb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgLOdrrS5QCNS9sxs77pHqtDVg-SDjn4w',
    appId: '1:1084522965422:android:84a8ccc3fc2fd0f339403f',
    messagingSenderId: '1084522965422',
    projectId: 'fir-flutter-codelab-cc3cb',
    storageBucket: 'fir-flutter-codelab-cc3cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxnXhxA7vU_faXScruzEmd7zZRzPC2Sfo',
    appId: '1:1084522965422:ios:5fa80a6d10a0727839403f',
    messagingSenderId: '1084522965422',
    projectId: 'fir-flutter-codelab-cc3cb',
    storageBucket: 'fir-flutter-codelab-cc3cb.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxnXhxA7vU_faXScruzEmd7zZRzPC2Sfo',
    appId: '1:1084522965422:ios:5fa80a6d10a0727839403f',
    messagingSenderId: '1084522965422',
    projectId: 'fir-flutter-codelab-cc3cb',
    storageBucket: 'fir-flutter-codelab-cc3cb.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
